import Foundation
import CasePaths

func generateFonts(arguments: [String]) {
  do {
    let path = try extractArgumentFlags(.path, arguments: arguments)
    let output = try extractArgumentFlags(.output, arguments: arguments)
    let outputPath = output.appending("/UIFonts.swift")
    let fileContent = try readFile(at: path)
    
    let modeValueNamedString = try modeStringNamedByNameListParser.parse(fileContent)
    let modeValueNameOrPixels = try modeNumberNamedOrPixelListParser.parse(fileContent)
    let modeValuePixels = modeValueNameOrPixels.compactMap { $0[case: \.pixel] }
    
    let modeValueNamedNumber = modeValueNameOrPixels.compactMap { $0[case: \.name] }
    let modeValueNamed = modeValueNamedString + modeValueNamedNumber
    
    let mobileNumberFontItems = try mobileNumbersModelTypeListParser.parse(fileContent)
      .compactMap { $0[case: \.font] }
    
    let mobileStringFontItems = try mobileStringModelTypeListParser.parse(fileContent)
      .compactMap { $0[case: \.font] }
    
    let mobileAllFontsItems = mobileNumberFontItems + mobileStringFontItems
    let groupedFonts = Dictionary(grouping: mobileAllFontsItems, by: { $0.font.value })
    let figmaModels = try groupedFonts
      .sorted { $0.key < $1.key}
      .map { key, items in
      try createFigmaFontModel(
        key: key,
        items: items,
        pixelValues: modeValuePixels,
        namedValues: modeValueNamed
      )
    }
    
    let properties = figmaModels.map(createStringProperty)
      .joined(separator: "\n\n")
    
    let familyEnumString = createFamilyStruct(items: figmaModels.map(\.value))
    let weightEnumString = createWeightStruct(items: figmaModels.map(\.value))
    
    // font sizes
    let smallFontSizes = try fontElementWithValueListParserWith(.small).parse(fileContent)
    let mediumFontSizes = try fontElementWithValueListParserWith(.medium).parse(fileContent)
    let xxLargeFontSizes = try fontElementWithValueListParserWith(.xxLarge).parse(fileContent)
    let xLargeFontSizes = try fontElementWithValueListParserWith(.xLarge).parse(fileContent)
    let fontSizes = try convertToString(small: smallFontSizes, medium: mediumFontSizes, xLarge: xLargeFontSizes, xxLarge: xxLargeFontSizes)

    let string = """
    import Foundation
    /// generated file by ResourceGen
    
    /// A structure representing a font definition generated from Figma design resources.
    ///
    /// This struct encapsulates the properties of a font, including its family, weight, size,
    /// line height, and letter spacing. It is designed to be used as a centralized source of truth
    /// for typography in an application, ensuring consistency between design and implementation.
    ///
    /// ## Properties
    /// - `family`: The font family, such as "Lora" or "TT Interphases Pro".
    /// - `weight`: The font weight, such as "Bold", "Demibold", or "Medium".
    /// - `size`: The font size in points.
    /// - `lineHeight`: The line height in points, defining the vertical spacing between lines of text.
    /// - `letterSpacing`: The letter spacing in points, controlling the spacing between characters.
    ///
    /// ## Usage
    /// Use predefined static properties like `articleBody` to access specific font configurations.
    /// These configurations are generated based on Figma design tokens, ensuring alignment with
    /// the design system.
    ///
    /// ```swift
    ///    Text("Label")
    ///      .gidFont(.articleBody)
    /// ```
    ///
    /// ## Conformance
    /// - `Equatable`: Allows comparison of two `FigmaFont` instances for equality.
    /// - `Sendable`: Ensures safe usage in concurrent contexts.
    ///
    /// > Note: This file is automatically generated by ResourceGen. Manual modifications may be overwritten.
    public struct FigmaFont: Equatable, Sendable {
      public let family: Family
      public let weight: Weight
      public let size: Double
      public let lineHeight: Double
      public let letterSpacing: Double
    
    \(familyEnumString)
    
    \(weightEnumString)
    
    \(properties)
    
    }
    
    \(fontSizes)
    """
    try writeFile(text: string, filename: outputPath)
    


  } catch {
    print(error)
    print(error.localizedDescription)
  }
}

@CasePathable
enum PixelOrName: Equatable, Sendable {
  case pixel(PixelModel)
  case name(NameModel)
}


func fontWeightConverter(_ value:  NameModel) throws -> NameModel {
  switch value.rawValue {
  case "400":
    return "regular"
  case "500":
    return "medium"
  case "600":
    return "semi"
  case "700":
    return "bold"
  default:
    throw ScriptError.message("unknown font weight")
  }
}

func convertToString(
  small: [FontElementWithValue],
  medium: [FontElementWithValue],
  xLarge: [FontElementWithValue],
  xxLarge: [FontElementWithValue]
) throws -> String {
  let elements = try convertFontElement(smalls: small, mediums: medium, xLarges: xLarge, xxLarges: xxLarge)
  let elementsStrings = elements.map(convertToString).joined(separator: "\n\n")
  
  let result = """
  public struct FigmaFontSize: Equatable, Sendable {
    public let smallSize: Double
    public let smallLineHeight: Double
    public let mediumSize: Double
    public let mediumLineHeight: Double
    public let xLargeSize: Double
    public let xLargeLineHeight: Double
    public let xxLargeSize: Double
    public let xxLargeLineHeight: Double

  \(elementsStrings)
  }
  """
  return result
}

func convertToString(font: FigmaFontSize) -> String {
  let name = camelCaseName(name: font.fontName)
  return """
    public static let \(name) = FigmaFontSize(
      smallSize: \(font.small.size),
      smallLineHeight: \(font.small.lineHeight),
      mediumSize: \(font.medium.size),
      mediumLineHeight: \(font.medium.lineHeight),
      xLargeSize: \(font.xLarge.size),
      xLargeLineHeight: \(font.xLarge.lineHeight),
      xxLargeSize: \(font.xxLarge.size),
      xxLargeLineHeight: \(font.xxLarge.lineHeight)
    )
  """
}

func convertFontElement(
  smalls: [FontElementWithValue],
  mediums: [FontElementWithValue],
  xLarges: [FontElementWithValue],
  xxLarges: [FontElementWithValue]
) throws -> [FigmaFontSize] {
  let smallValues = try convertFontElementSizes(elements: smalls)
  let mediumValues = try convertFontElementSizes(elements: mediums)
  let xLargeValues = try convertFontElementSizes(elements: xLarges)
  let xxLargeValues = try convertFontElementSizes(elements: xxLarges)
  
  return try smallValues.map { small in
    guard let medium = mediumValues.first(where: { $0.name == small.name }) else {
      throw ScriptError.message("font size and medium names must be the same")
    }
    guard let xLarge = xLargeValues.first(where: { $0.name == small.name }) else {
      throw ScriptError.message("font size and xLarge names must be the same")
    }
    
    guard let xxLarge = xxLargeValues.first(where: { $0.name == small.name }) else {
      throw ScriptError.message("font size and xxLarge names must be the same")
    }
    return FigmaFontSize(
      fontName: small.name,
      small: small.value,
      medium: medium.value,
      xLarge: xLarge.value,
      xxLarge: xxLarge.value
    )
  }
}

func convertFontElementSizes(elements: [FontElementWithValue]) throws -> [(name: NameModel, value: FigmaFontSize.FontSize)] {
  let sizes = elements.filter { $0[case: \.fontPixel]?.font[case: \.size] != nil }
  let lineHeights = elements.filter { $0[case: \.fontPixel]?.font[case: \.lineHeight] != nil }
  
  return try sizes.map { size in
    guard let lineHeight = lineHeights.first(where: { $0.font.value == size.font.value}) else {
      throw ScriptError.message("font size and line height names must be the same")
    }
    return try (
      name: size.font.value,
      value: convertFontElementSize(sizeFont: size, lineHeightFont: lineHeight)
    )
  }
}

func convertFontElementSize(sizeFont: FontElementWithValue, lineHeightFont: FontElementWithValue) throws -> FigmaFontSize.FontSize {
  guard sizeFont.font[case: \.size] == lineHeightFont.font[case: \.lineHeight] else {
    throw ScriptError.message("fonts size and line height names must be the same")
  }
  
  let size = sizeFont[case: \.fontPixel]?.pixel.rawValue
  let lineHeight = lineHeightFont[case: \.fontPixel]?.pixel.rawValue
  
  guard let size , let lineHeight else {
    // must implemented get size and lineHeight for fontVar
    throw ScriptError.message("fonts size and line must not be nil")
  }
  
  return .init(
    size: size ,
    lineHeight: lineHeight
  )
}

func createStringProperty(key: NameModel, item: FigmaFontModel) -> String {
  let keyName = camelCaseName(name: key)
  let string = """
      /// family: \(camelCaseName(name: item.family))
      /// weight: \(camelCaseName(name: item.weight))
      /// size: \(item.size.rawValue)
      /// lineHeight: \(item.lineHeight.rawValue)
      /// letterSpacing: \(item.letterSpacing.rawValue)
      public static var \(keyName): FigmaFont {
        FigmaFont(
          family: .\(camelCaseName(name: item.family)),
          weight: .\(camelCaseName(name: item.weight)),
          size: \(item.size.rawValue),
          lineHeight: \(item.lineHeight.rawValue),
          letterSpacing: \(item.letterSpacing.rawValue)
        )
      }
    """
  return string
}

func createFigmaFontModel(
  key: NameModel,
  items: [FontNameVarModel],
  pixelValues: [NamedPixel],
  namedValues: [NameByNameModel])
throws -> (key: NameModel, value: FigmaFontModel) {
  let family = try items.first(where: { $0.font[case: \.family] != nil })
    .flatMap { try getFontValue(item: $0, pixelValues: pixelValues, namedValues: namedValues) }
    .flatMap { $0[case: \.name] }
  
  let weight = try items.first(where: { $0.font[case: \.weight] != nil })
    .flatMap { try getFontValue(item: $0, pixelValues: pixelValues, namedValues: namedValues) }
    .flatMap { $0[case: \.name] }
  
  let size = try items.first(where: { $0.font[case: \.size] != nil })
    .flatMap { try getFontValue(item: $0, pixelValues: pixelValues, namedValues: namedValues) }
    .flatMap { $0[case: \.pixel] }
  
  let lineHeight = try items.first(where: { $0.font[case: \.lineHeight] != nil })
    .flatMap { try getFontValue(item: $0, pixelValues: pixelValues, namedValues: namedValues) }
    .flatMap { $0[case: \.pixel] }
  
  let letterSpacing = try items.first(where: { $0.font[case: \.letterSpacing] != nil })
    .flatMap { try getFontValue(item: $0, pixelValues: pixelValues, namedValues: namedValues) }
    .flatMap { $0[case: \.pixel] }
  
  guard let family, let weight, let size, let lineHeight, let letterSpacing else {
    throw ScriptError.message("--Figma Font cant generate: \(key) family: \(String(describing: family)) weight: \(String(describing: weight)) size: \(String(describing: size)) lineHeight: \(String(describing: lineHeight))  letterSpacing: \(String(describing: letterSpacing))")
  }

  return try (
    key,
    FigmaFontModel(
      family: family,
      weight: fontWeightConverter(weight),
      size: size,
      lineHeight: lineHeight,
      letterSpacing: letterSpacing
    )
  )
}

func getFontValue(item: FontNameVarModel, pixelValues: [NamedPixel], namedValues: [NameByNameModel]) throws -> PixelOrName {
  switch item.font {
    case let .family(name):
      guard let value = namedValues.first(where: { $0.first == item.varName })?.second else {
        throw ScriptError.message("--family not found: \(name)")
      }
      return .name(value)
    case let .weight(name):
      guard let value = namedValues.first(where: { $0.first == item.varName })?.second else {
        throw ScriptError.message("--weight not found: \(name)")
      }
      return .name(value)
    case let .size(name):
      guard let value = pixelValues.first(where: { $0.name == item.varName })?.pixel else {
        throw ScriptError.message("--pixel not found: \(name)")
      }
      return .pixel(value)
    case let .lineHeight(name):
      guard let value = pixelValues.first(where: { $0.name == item.varName })?.pixel else {
        throw ScriptError.message("--line height not found: \(name)")
      }
      return .pixel(value)
    case let .letterSpacing(name):
      guard let value = pixelValues.first(where: { $0.name == item.varName })?.pixel else {
        throw ScriptError.message("--letter spacing not found: \(name)")
      }
      return .pixel(value)
  }
}

func createFamilyStruct(items: [FigmaFontModel]) -> String {
  let families = Set(items.map(\.family))
    .map { family in
      "    case \(camelCaseName(name: family))"
    }
    .sorted()
    .joined(separator: "\n")
  
  let string = """
    public enum Family: Sendable {
  \(families)
    }
  """
  return string
}


func createWeightStruct(items: [FigmaFontModel]) -> String {
  let weights = Set(items.map(\.weight))
    .map { weight in
      "    case \(camelCaseName(name: weight))"
    }
    .sorted()
    .joined(separator: "\n")
  
  let string = """
    public enum Weight: Sendable {
  \(weights)
    }
  """
  return string
}
